version: 2

jobs:  
  build:
    working_directory: ~/code
    
    docker:
      - image: circleci/android:api-26-alpha

    environment:
      JAVA_HOME: /usr/lib/jvm/jdk1.8.0
      ANDROID_HOME: /usr/local/android-sdk-linux
      ANDROID_NDK_HOME: /usr/local/android-sdk-linux/ndk-bundle
      ANDROID_NDK: /usr/local/android-sdk-linux/ndk-bundle
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      
    branches:
      only:
        - test

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          
      - run:
          name: Environmental Variable Setting
          command: |
            echo 'ANDLOILO_KEY_PASSWORD='$ANDLOILO_KEY_PASSWORD >> gradle.properties
            echo 'ANDLOILO_KEYSTORE_PASSWORD='$ANDLOILO_KEYSTORE_PASSWORD >> gradle.properties

      - run:
          name: Run Tests
          command: ./gradlew clean assembleRelease

      - run:
          name: Run Build For AndroidTest
          command: ./gradlew assembleAndroidTest
          
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release

      - store_artifacts:
          path: app/build/outputs/apk/androidTest
          destination: androidTest

