version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    branches:
      only:
        - test

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew clean assembleRelease

      - run:
          name: Run Build For AndroidTest
          command: ./gradlew assembleAndroidTest
          
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release

      - store_artifacts:
          path: app/build/outputs/apk/androidTest
          destination: androidTest

