version: 2

jobs:  
  build:
    working_directory: ~/code
    
    docker:
      - image: circleci/android:api-26-alpha

    environment:
      JAVA_HOME: /usr/lib/jvm/jdk1.8.0
      ANDROID_HOME: /usr/local/android-sdk-linux
      ANDROID_NDK_HOME: /usr/local/android-sdk-linux/ndk-bundle
      ANDROID_NDK: /usr/local/android-sdk-linux/ndk-bundle
      # _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      # GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      
    branches:
      only:
        - test

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          
      - run:
          name: Set Environmental Variables
          command: |
            git submodule init && git submodule update
            wget https://dl.google.com/android/repository/android-ndk-r14-linux-x86_64.zip -P /usr/local/android-sdk-linux
            echo y | unzip -d /usr/local/android-sdk-linux /usr/local/android-sdk-linux/android-ndk-r14-linux-x86_64.zip
            sudo mv /usr/local/android-sdk-linux/android-ndk-r14 /usr/local/android-sdk-linux/ndk-bundle
            mkdir $ANDROID_HOME/licenses
            echo `cat android-sdk-license` > $ANDROID_HOME/licenses/android-sdk-license
            echo "sdk.dir="$ANDROID_HOME > local.properties
            echo "ndk.dir="$ANDROID_NDK >> local.properties
            echo "" >> gradle.properties
            echo "ANDLOILO_KEY_PASSWORD="$ANDLOILO_KEY_PASSWORD >> gradle.properties
            echo "ANDLOILO_KEYSTORE_PASSWORD="$ANDLOILO_KEYSTORE_PASSWORD >> gradle.properties
            mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew clean assembleRelease

      - run:
          name: Run Build For AndroidTest
          command: ./gradlew assembleAndroidTest
          
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release

      - store_artifacts:
          path: app/build/outputs/apk/androidTest
          destination: androidTest
